INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (1,'small','gluten free','thin','tomato',1,10.14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (1,14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (1,1);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (1,16);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (1,5);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (2,'x-large','gluten free','thin','artichoke',0,22.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (3,'small','whole wheat','stuffed','bar bq',0,8.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (4,'medium','whole wheat','thin','habanero',1,14.29);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (4,15);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (4,7);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (4,1);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (4,2);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (4,8);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (5,'medium','whole wheat','stuffed','bar bq',0,18.14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (5,10);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (5,13);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (5,8);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (5,11);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (6,'large','whole wheat','hand tossed','bar bq',1,18.14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (6,1);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (6,15);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (6,11);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (6,2);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (7,'large','regular','thin','tomato',0,21.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (7,7);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (7,13);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (7,15);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (8,'scorpio','gluten free','regular','pesto',0,106.14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (8,7);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (8,12);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (8,10);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (8,13);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (9,'scorpio','gluten free','NY style','habanero',1,104.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (9,9);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (9,6);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (10,'x-large','whole wheat','NY style','pesto',0,22.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (11,'medium','whole wheat','hand tossed','alfredo',1,16.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (12,'medium','regular','stuffed','pesto',1,14.29);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (12,13);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (12,2);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (12,14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (12,8);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (12,7);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (13,'large','whole wheat','stuffed','alfredo',0,21.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (13,15);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (13,5);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (13,14);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (14,'small','whole wheat','NY style','artichoke',0,13.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (14,11);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (14,12);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (15,'large','gluten free','stuffed','tomato',0,21.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (16,'x-large','whole wheat','stuffed','alfredo',1,27.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (16,12);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (17,'x-large','gluten free','thin','artichoke',1,22.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (17,9);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (17,8);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (18,'small','regular','regular','habanero',1,8.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (18,3);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (18,14);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (19,'scorpio','regular','NY style','alfredo',1,104.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (19,6);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (19,14);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (20,'small','gluten free','thin','habanero',0,13.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (21,'large','whole wheat','regular','habanero',0,16.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (21,12);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (22,'x-large','regular','stuffed','bar bq',1,27.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (22,10);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (23,'x-large','regular','hand tossed','alfredo',0,22.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (24,'small','whole wheat','NY style','pesto',1,13.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (24,3);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (24,6);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (24,7);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (25,'large','regular','hand tossed','alfredo',0,16.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (25,12);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (26,'scorpio','gluten free','stuffed','tomato',1,99.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (27,'x-large','whole wheat','thin','artichoke',1,27.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (28,'large','regular','NY style','habanero',1,21.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (29,'x-large','gluten free','stuffed','bar bq',1,22.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (30,'large','gluten free','regular','tomato',0,21.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (30,5);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (30,13);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (31,'medium','gluten free','stuffed','alfredo',0,16.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (31,8);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (31,14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (31,6);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (32,'large','whole wheat','NY style','alfredo',1,23.14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (32,9);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (32,8);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (32,10);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (32,13);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (33,'large','gluten free','NY style','artichoke',1,21.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (33,7);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (34,'medium','whole wheat','thin','alfredo',1,16.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (34,13);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (34,2);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (35,'large','whole wheat','stuffed','habanero',1,21.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (36,'medium','whole wheat','NY style','bar bq',0,18.14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (36,16);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (36,6);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (36,3);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (36,2);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (37,'small','gluten free','regular','alfredo',0,13.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (38,'x-large','whole wheat','thin','habanero',0,25.29);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (38,10);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (38,2);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (38,16);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (38,9);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (38,12);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (39,'x-large','gluten free','NY style','artichoke',1,27.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (40,'scorpio','regular','regular','pesto',1,99.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (40,12);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (41,'small','whole wheat','NY style','artichoke',0,8.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (41,7);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (41,12);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (41,2);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (42,'scorpio','regular','thin','habanero',1,99.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (42,3);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (43,'scorpio','regular','stuffed','tomato',0,104.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (44,'x-large','regular','thin','pesto',1,27.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (45,'large','regular','NY style','bar bq',1,16.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (45,10);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (45,3);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (46,'large','regular','NY style','pesto',1,16.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (46,2);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (46,13);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (46,8);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (47,'x-large','regular','hand tossed','bar bq',0,27.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (47,3);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (47,7);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (48,'small','gluten free','NY style','artichoke',0,8.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (48,2);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (48,3);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (48,12);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (49,'scorpio','regular','stuffed','habanero',0,104.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (50,'scorpio','gluten free','regular','alfredo',0,104.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (50,14);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (51,'scorpio','regular','regular','alfredo',1,99.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (51,12);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (52,'x-large','whole wheat','hand tossed','alfredo',1,22.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (53,'large','gluten free','regular','bar bq',1,23.14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (53,6);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (53,2);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (53,3);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (53,5);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (54,'small','regular','regular','alfredo',1,13.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (54,12);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (54,9);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (55,'medium','whole wheat','thin','bar bq',0,14.29);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (55,5);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (55,1);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (55,10);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (55,11);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (55,9);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (56,'scorpio','whole wheat','hand tossed','habanero',0,99.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (56,10);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (56,4);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (57,'x-large','whole wheat','NY style','pesto',1,27.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (57,12);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (57,2);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (58,'x-large','whole wheat','regular','bar bq',0,27.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (58,13);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (58,1);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (58,4);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (59,'medium','whole wheat','hand tossed','habanero',0,11.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (59,4);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (59,15);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (60,'scorpio','whole wheat','NY style','tomato',0,99.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (60,9);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (60,14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (60,15);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (61,'small','regular','thin','pesto',1,8.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (62,'medium','whole wheat','regular','bar bq',1,16.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (63,'small','regular','hand tossed','artichoke',0,13.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (63,10);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (64,'x-large','gluten free','regular','habanero',0,22.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (64,6);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (64,2);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (65,'large','whole wheat','NY style','alfredo',1,16.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (66,'medium','regular','thin','habanero',1,11.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (67,'medium','regular','thin','alfredo',0,11.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (68,'x-large','whole wheat','thin','bar bq',0,22.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (69,'scorpio','gluten free','regular','alfredo',0,99.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (70,'small','regular','NY style','alfredo',0,10.14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (70,16);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (70,11);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (70,10);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (70,7);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (71,'small','gluten free','hand tossed','bar bq',0,15.14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (71,2);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (71,5);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (71,10);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (71,7);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (72,'small','regular','thin','tomato',0,16.29);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (72,11);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (72,2);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (72,7);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (72,12);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (72,8);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (73,'large','whole wheat','NY style','artichoke',1,16.99);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (74,'medium','gluten free','hand tossed','pesto',0,16.99);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (74,14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (74,11);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (74,15);
INSERT INTO pizzas (pizzaID, size, dough,crustStyle,sauce,delivery,price) VALUES (75,'small','gluten free','thin','habanero',0,10.14);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (75,10);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (75,1);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (75,6);
INSERT INTO toppingsonpizza (pizzaID, toppingID) VALUES (75,5);
